#!/bin/sh
mkdir lite-server
cd ./lite-server

npm init
# Accept defaults and set entry point as 'index.html'

npm install lite-server --save-dev   # in .gitignore, you have to explicitly install this module to run the server
# git init
# Not issued the previous command because we are in a git repository
# You should do it in an external folder if you want to complete the test with git
echo 'node_modules' > .gitignore

# Modify 'packaje.json' to define "scripts" as a minimum
{
  "name": "git-test",
  "version": "1.0.0",
  "description": "This is the Git and Node basic learning project",
  "main": "index.html",
  "scripts": {
    "start": "npm run lite",
    "test": "echo \"Error: no test specified\" && exit 1",
    "lite": "lite-server"
  },
  "repository": {
    "type": "git",
    "url": "git+https://jogesh_k_muppala@bitbucket.org/jogesh_k_muppala/git-test.git"
  },
  "author": "",
  "license": "ISC",
  "homepage": "https://bitbucket.org/jogesh_k_muppala/git-test#readme",
  "devDependencies": {
    "lite-server": "^2.2.2"
  }
}

# Now add 'index.html' file, that you set before as the entry point

<!DOCTYPE html>
<html>

<head>
  <title>Page Title</title>
</head>

<body>
The content of the document......
</body>

</html>

# Then start the server
npm start

# Change the line within the body html tag to whatever else
<body>
This is the first paragraph......
</body>

# Browsersync component of module 'lite-server' will automatically refresh the web page after saving changes in 'index.html'
